export const ARTICLE_CARD_COLUMNS = {
  id: true,
  title: true,
  slug: true,
  excerpt: true,
  heroImage: true,
  heroImageAlt: true,
  heroImageCaption: true,
  status: true,
  isFeatured: true,
  isEditorsPick: true,
  isBreaking: true,
  isTrending: true,
  isLatest: true,
  isBriefing: true,
  isGlobalBriefing: true,
  publishedAt: true,
  readingTimeMinutes: true,
  viewCount: true,
  categoryId: true,
  secondaryCategoryIds: true,
  authorId: true,
  createdAt: true,
  updatedAt: true,
} as const;
