export const ARTICLE_CARD_COLUMNS = {
  id: true,
  title: true,
  slug: true,
  excerpt: true,
  heroImage: true,
  heroImageAlt: true,
  heroImageCaption: true,
  status: true,
  isFeatured: true,
  isEditorsPick: true,
  isBreaking: true,
  isTrending: true,
  isLatest: true,
  isBriefing: true,
  isGlobalBriefing: true,
  publishedAt: true,
  readingTimeMinutes: true,
  viewCount: true,
  categoryId: true,
  secondaryCategoryIds: true,
  authorId: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const STATIC_FALLBACK_CATEGORIES: Record<string, { id: number; name: string; slug: string; description: string; icon: string; color: string; parentId: number | null; isActive: boolean }> = {
  phone: { id: 2, name: "Phone", slug: "phone", description: "Latest smartphone news, launches, reviews and updates from Apple, Samsung, Google and more. Stay ahead on iPhone, Android and mobile tech with TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#0ea5e9", parentId: null, isActive: true },
  audio: { id: 3, name: "Audio", slug: "audio", description: "Headphone, earbud and speaker news, launches and reviews. Explore the latest audio gear from Sony, Bose, Apple and more on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#8b5cf6", parentId: null, isActive: true },
  robotics: { id: 4, name: "Robotic", slug: "robotic", description: "Robotics news covering humanoid robots, automation, AI hardware and industry funding. Track the machines shaping the future of work on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#6366f1", parentId: null, isActive: true },
  robotic: { id: 4, name: "Robotic", slug: "robotic", description: "Robotics news covering humanoid robots, automation, AI hardware and industry funding. Track the machines shaping the future of work on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#6366f1", parentId: null, isActive: true },
  fitness: { id: 5, name: "Fitness", slug: "fitness", description: "Fitness tech news on smartwatches, wearables, fitness trackers and health gadgets. Find the latest launches and trends to power your workouts on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#10b981", parentId: null, isActive: true },
  security: { id: 6, name: "Security", slug: "security", description: "Cybersecurity news on data breaches, hacks, privacy threats and zero-day flaws. Stay informed and protect your data with TechCrest's security coverage.", icon: "/icons/techcrest-icon.svg", color: "#f59e0b", parentId: null, isActive: true },
  ai: { id: 7, name: "AI", slug: "ai", description: "Latest AI news on ChatGPT, LLMs, machine learning, AI startups and funding. Get fast updates and expert analysis on artificial intelligence at TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#a855f7", parentId: null, isActive: true },
  "smart-home": { id: 8, name: "Home", slug: "home", description: "Smart home news on connected devices, hubs, appliances and home automation. Discover the latest gadgets and updates for a smarter home on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#14b8a6", parentId: null, isActive: true },
  home: { id: 8, name: "Home", slug: "home", description: "Smart home news on connected devices, hubs, appliances and home automation. Discover the latest gadgets and updates for a smarter home on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#14b8a6", parentId: null, isActive: true },
  evs: { id: 9, name: "EVs", slug: "evs", description: "Electric vehicle news on Tesla, EV launches, charging tech, self-driving and robotaxis. Follow the future of mobility with TechCrest's EV coverage.", icon: "/icons/techcrest-icon.svg", color: "#22c55e", parentId: null, isActive: true },
  crypto: { id: 10, name: "Crypto", slug: "crypto", description: "Crypto news on Bitcoin, stablecoins, exchanges, blockchain and Web3. Get the latest cryptocurrency updates and market-moving stories on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#f97316", parentId: null, isActive: true },
  gaming: { id: 11, name: "Gaming", slug: "gaming", description: "Gaming news on consoles, PC games, Xbox, PlayStation, Nintendo and esports. Catch the latest game launches, industry updates and trends on TechCrest.", icon: "/icons/techcrest-icon.svg", color: "#ef4444", parentId: null, isActive: true },
  deals: { id: 12, name: "Deals", slug: "deals", description: "Best tech deals, discounts, and offers", icon: "/icons/techcrest-icon.svg", color: "#ec4899", parentId: null, isActive: true },
};

